#!/usr/bin/env python3
"""Regenerate ba-actions.md from ba-actions.json (canonical). Never hand-edit the MD."""

from __future__ import annotations

import json
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
JSON_PATH = ROOT / "ba-actions.json"
MD_PATH = ROOT / "ba-actions.md"

PRIORITY_ORDER = {"high": 0, "medium": 1, "low": 2}
STATUS_OPEN = {"open", "in_progress", "blocked"}
WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
MONTHS = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]


def parse_iso_date(s: str | None) -> date | None:
    if not s:
        return None
    return date.fromisoformat(s[:10])


def friendly_date(d: date | None) -> str:
    if d is None:
        return "—"
    return f"{WEEKDAYS[d.weekday()]} {d.day} {MONTHS[d.month - 1]}"


def friendly_datetime(iso: str | None) -> str:
    if not iso:
        return "unknown"
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        if dt.tzinfo:
            dt = dt.astimezone()
        hour = dt.hour % 12 or 12
        meridiem = "pm" if dt.hour >= 12 else "am"
        return (
            f"{WEEKDAYS[dt.weekday()]} {dt.day} {MONTHS[dt.month - 1]} "
            f"{dt.year}, {hour}:{dt.minute:02d} {meridiem}"
        )
    except ValueError:
        return iso


def status_label(action: dict) -> str:
    if action.get("blocked") or action.get("status") == "blocked":
        return "Blocked"
    return {
        "open": "Open",
        "in_progress": "In Progress",
        "done": "Done",
        "cancelled": "Cancelled",
    }.get(action.get("status", "open"), str(action.get("status", "open")).title())


def sort_open(actions: list[dict]) -> list[dict]:
    def key(a: dict):
        blocked = 0 if (a.get("blocked") or a.get("status") == "blocked") else 1
        pri = PRIORITY_ORDER.get(a.get("priority", "medium"), 9)
        due = parse_iso_date(a.get("due")) or date.max
        raised = parse_iso_date(a.get("raised")) or date.max
        return (blocked, pri, due, raised)

    return sorted(actions, key=key)


def main() -> int:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    sync_iso = data.get("last_synced") or datetime.now().astimezone().isoformat()
    sync_dt = datetime.fromisoformat(sync_iso.replace("Z", "+00:00"))
    if sync_dt.tzinfo:
        sync_dt = sync_dt.astimezone()
    today = sync_dt.date()
    tomorrow = date.fromordinal(today.toordinal() + 1)

    actions = data.get("actions", [])
    watching = data.get("watching", [])

    open_actions = [a for a in actions if a.get("status") in STATUS_OPEN]
    closed_actions = [a for a in actions if a.get("status") in {"done", "cancelled"}]
    blocked_count = sum(
        1 for a in open_actions if a.get("blocked") or a.get("status") == "blocked"
    )

    overdue = [
        a
        for a in open_actions
        if (d := parse_iso_date(a.get("due"))) is not None and d < today
    ]

    reminders: list[tuple[str, dict]] = []
    for a in open_actions:
        ro = parse_iso_date(a.get("remind_on"))
        if ro is None:
            continue
        if ro < today:
            bucket = "Overdue"
        elif ro == today:
            bucket = f"Today — {friendly_date(today)}"
        elif ro == tomorrow:
            bucket = f"Tomorrow — {friendly_date(tomorrow)}"
        else:
            bucket = f"Upcoming — {friendly_date(ro)}"
        reminders.append((bucket, a))

    reminder_order = {"Overdue": 0}
    reminders.sort(key=lambda x: (reminder_order.get(x[0], 1), x[0], x[1].get("task", "")))

    closed_actions.sort(key=lambda a: a.get("last_updated") or "", reverse=True)

    lines: list[str] = [
        "# BA actions (auto-generated)",
        "",
        f"**Last synced:** {friendly_datetime(sync_iso)}",
        (
            f"**Open:** {len(open_actions)} | **Blocked:** {blocked_count} | "
            f"**Overdue:** {len(overdue)} | **Closed:** {len(closed_actions)}"
        ),
        "",
        "Canonical store: `_workstream/ba-actions.json`. **Do not edit this file by hand.**",
        "Regenerate: `py _workstream/regenerate-ba-actions-md.py` after any JSON change.",
        "",
        "---",
        "",
    ]

    if reminders:
        lines.append("## Reminders (start-by dates)")
        lines.append("")
        current_bucket = None
        for bucket, a in reminders:
            if bucket != current_bucket:
                if current_bucket is not None:
                    lines.append("")
                lines.append(f"### {bucket}")
                lines.append("")
                lines.append("| Task | Reminder | Due |")
                lines.append("|------|----------|-----|")
                current_bucket = bucket
            due = friendly_date(parse_iso_date(a.get("due")))
            reminder = (a.get("reminder") or "—").replace("|", "/")
            task = a.get("task", "").replace("|", "/")
            lines.append(f"| {task} | {reminder} | {due} |")
        lines.extend(["", "---", ""])
    else:
        lines.extend(
            ["## Reminders (start-by dates)", "", "No start-by reminders set.", "", "---", ""]
        )

    lines.extend(["## Open actions", ""])
    if open_actions:
        lines.append("| Status | Priority | Due | Initiative | Task |")
        lines.append("|--------|----------|-----|------------|------|")
        for a in sort_open(open_actions):
            due = friendly_date(parse_iso_date(a.get("due")))
            init = a.get("initiative") or "—"
            task = a.get("task", "").replace("|", "/")
            pri = (a.get("priority") or "medium").title()
            lines.append(f"| {status_label(a)} | {pri} | {due} | {init} | {task} |")
    else:
        lines.append("No open actions.")
    lines.extend(["", "Full JSON: `_workstream/ba-actions.json`", "", "---", ""])

    if watching:
        lines.extend(["## Watching (others)", ""])
        lines.append("| Owner | Due | Task |")
        lines.append("|-------|-----|------|")
        for w in watching:
            owner = w.get("owner", "—")
            due = friendly_date(parse_iso_date(w.get("due")))
            task = w.get("task", "").replace("|", "/")
            lines.append(f"| {owner} | {due} | {task} |")
        lines.extend(["", "---", ""])

    lines.extend(["## Closed actions", ""])
    if closed_actions:
        lines.append("| Status | Closed | Task | Notes |")
        lines.append("|--------|--------|------|-------|")
        for a in closed_actions[:30]:
            notes = (a.get("notes") or "—").replace("|", "/").replace("\n", " ")
            if len(notes) > 120:
                notes = notes[:117] + "..."
            task = a.get("task", "").replace("|", "/")
            closed = friendly_date(parse_iso_date((a.get("last_updated") or "")[:10]))
            st = status_label(a)
            lines.append(f"| {st} | {closed} | {task} | {notes} |")
        if len(closed_actions) > 30:
            lines.append("")
            lines.append(f"*…and {len(closed_actions) - 30} more closed in JSON.*")
    else:
        lines.append("No closed actions.")

    lines.extend(
        [
            "",
            f"Gate: ba-actions-md-regen: PASS ({len(open_actions)} open, derived from JSON)",
            "",
        ]
    )

    MD_PATH.write_text("\n".join(lines), encoding="utf-8")

    now = datetime.now().astimezone().isoformat()
    data["last_generated_md"] = now
    JSON_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Regenerated {MD_PATH} ({len(open_actions)} open, {len(closed_actions)} closed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
